pipeline {
  agent any
  
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    
    stage('Build') {
      steps {
        mvn clean install
      }
    }
    
    stage('Test') {
      steps {
        mvn validate
      }
    }
    
    stage('Deploy') {
      steps {
               
        // Copy artifact to EC2 instance via SSH
        sh "scp -i /path/to/ssh/key.pem /var/Jenkins_workspace ubuntu@<EC2_INSTANCE_IP>:~/"
        
        // Connect to EC2 instance via SSH and execute deployment commands
        sh "ssh -i /path/to/ssh/key.pem ubuntu@<EC2_INSTANCE_IP> 'sudo systemctl stop tomcat.service && sudo mv ~/artifact /var/lib/tomcat9/webapps && sudo systemctl start tomcat.service'"
      }
    }
  }
}
